### ISSUE TITLE
Making crystal from polygon

### ISSUE THREAD

**Issue by EthanJUCB** [C-CINA/focus#244] opened 2019-10-04 02:57 UTC
Hi all,

I had a problem when I tried to make crystal from polygon. It happened to both the latest and the old version in Centos7.

=======================================================================================================================================================================================================
==== modifypolygon - to prepare the input data for boximage ===========================================================================================================================================
=======================================================================================================================================================================================================
 
Using as original polygon file:
1837.44, 1837.44    ! X,Y dimensions of the original image, origin bottom left (0,0)
93, 2180
77, 1372
2660, 44
3221, 78
3171, 1570
188, 2196
108, 2176
 
##########################2dx_maskCrystal finished.###########################
At line 30 of file /local0/hudson/jenkins/buildst01/jenkins/buildst01/workspace/focus_nightly_build/label/fedora/kernel/mrc/source/2dx_modifypolygon.for (unit = 11, file = 'selectionList.dat') 
Fortran runtime error: Bad integer for item 1 in list input 

I checked 'selectionList.dat' , it looked normal, then I ran the 2dx_modifypolygon.exe in terminal. There was no response from this command. Other 2dx commands in /kernel/mrc/bin worked properly.

Any suggestions, many thanks.

Best 
Xi

**Comment by rdrighetto** [comment] 2019-10-08 16:29
Dear Xi,

Sorry, I was not able to reproduce the issue. Could you please provide a screenshot of the polygon and the 'selectionList.dat' file?

Also, maybe this is a CentOS and/or gfortran issue from our continuous integration issue. I will try to test the .rpm binary here. In the meantime, would it be possible for you to try e.g. the .deb version of the binary, or compile from source?

Or maybe @sthennin already knows this issue or a possible solution?

**Comment by EthanJUCB** [comment] 2019-10-08 18:44
Hi Ricardo,

Thanks very much. 
Make polygon works now after I upgraded to the latest version using RPM. However, I had new issue when I came back to make FFT for the the masked image. Please see attached information. 

Sure, I will try to build from source.

Best 
Xi

#################################2dx_fftrans##################################
 
############################################
# Parameters requested by the Script       #
############################################
phaseori_done = n
tempkeep = n
imagename = mimage_2dx
nonmaskimagename = image_2dx
imagenumber = 0000002295
imagesidelength = 3300
realcell = 9,38
magnification = 89798.9
stepdigitizer = 5.0
calc_from_sample_pixel = y
sample_pixel = 0.5568
realang = 90.0
phacon = 0.995
resmin = 200.0
resmax = 2.0
radlim = 35.0,35.0,0.0
generateperiodogram = n
periodogramwindowsize = 512
periodogramnumsubsteps = 20
taperbeforefft = y
crop = 1
crop_histogram = y
crop_histogram_percent = 5
crop_histogram_stdev = 4.0
ctfcor_imode = 1
use_masked_image = y
movie_inmovie = n
movie_stackname = movie_aligned
 
############################################
# Parameters from the Preferences settings #
############################################
app_python = /usr/bin/python2.7
app_cadaver = /usr/bin/cadaver
app_anaconda = /usr/bin/python2.7
dir_ccp4 = /home/xijiang/Downloads/ccp4-7.0
app_gawk = /usr/local/Cellar/gawk
cuda_library = /usr/local/cuda/lib64
app_unblur = /usr/local/cina/unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe
app_motioncor2 = /usr/local/cina/motioncor2/bin/motioncor2.exe
app_gctf = /home/xijiang/Downloads/Gctf_v1.06/bin/Gctf-v1.06_sm_30_cu8.0_x86_64
app_ctffind = /home/xijiang/Downloads/CTFFIND4/bin/ctffind
app_gautomatch = /usr/local/cina/Gautomatch/0.50_cuda7.5/bin/gautomatch
dir_eman2 = /usr/local/EMAN2
dir_imod = /usr/local/IMOD
dir_frealign = /home/xijiang/Downloads/frealign-2dx-master
dir_relion = /usr/local/relion
Microscope_Name = CryoEM
Default_CS = 2.6
Default_KV = 300.0
Default_phase_shift_doit = n
status_folder_update = n
status_folder = none
status_microscope = Titan
status_refresh_rate = 0
status_webdav = http://my.server.com/files <http://my.server.com/files>
website_blur_doit = y
website_blurkernel = 7
SCRATCH_DISK = .
FAST_DISK = .
GPU_how_many = 4
GPU_to_use = 0 1 2 3
GPU_cycle = n
MotionCor2_alone = y
notify_email_admin = y
notify_email_admin_adress = name@provider.com <mailto:name@provider.com>
notify_last_minutes = 15
notify_delay_minutes = 60
notify_lastnumber = 50
notify_limit_mild = 30
notify_limit_severe = 15
flag_isdark_threshold = 0.1
flag_hasstripe_threshold = 38.0
flag_hastoohighdefocus_threshold = 7.0
flag_hastoolowdefocus_threshold = 0.2
flag_icinesstoohigh_threshold = 1.6
flag_drifttoohigh_threshold = 50.0
flag_astigmatismtoohigh_threshold = 0.03
flag_ctfresolutiontoobad_threshold = 8.0
 
#############################################
# Now the remainder of the original script: #
#############################################
 
++++++++++++++++++++++++++++++++
Initializing script environment
++++++++++++++++++++++++++++++++
 
 Running the following shell:
  version tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,color,filec
 
date = Tue Oct 8 11:07:32 PDT 2019
system = Linux
bin_2dx = /opt/focus/kernel/mrc/bin
proc_2dx = /opt/focus/scripts/proc
==== dir_eman2 = /usr/local/EMAN2 =====================================================================================================================================================================
==== app_python = /usr/bin/python2.7 ==================================================================================================================================================================
==== app_anaconda = /usr/bin/python2.7 ================================================================================================================================================================
==== dir_frealign = /home/xijiang/Downloads/frealign-2dx-master =======================================================================================================================================
==== dir_relion = /usr/local/relion ===================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== RELION installation directory not found. Is it installed ??? =====================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== /usr/local/relion ================================================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== The location of RELION installation is defined in Preferences. ===================================================================================================================================
=======================================================================================================================================================================================================
 
 
 
=======================================================================================================================================================================================================
==== Sourcing 2dx_init_files_sub.com <http://2dx_init_files_sub.com/> ==================================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Setting imagename to image_2dx.mrc ===============================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Testing if image_2dx.mrc exists ==================================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Copying image_2dx_raw.mrc onto image_2dx.mrc =====================================================================================================================================================
=======================================================================================================================================================================================================
 
############################2dx_fftrans finished.#############################
cp: ?image_2dx_raw.mrc? and ?image_2dx.mrc? are the same file

**Comment by sthennin** [comment] 2019-10-09 11:42
Dear Xi,
Your polygon file starts with a floating point number
1837.44, 1837.44 ! X,Y dimensions of the original image, origin bottom left (0,0)
That is very odd. An image cannot have 1837.44 pixels in one row. How did you get these dimensions of the image file? Those should be integers. The program in charge to read that expects integers. I don't want to change that, since it would be important to verify where your polygon image dimensions come from.  How did you get that file?

**Comment by klhvorecny** [comment] 2019-11-04 18:26
Hello,

I am receiving the same error that Xi mentions above (see below for the text of the error). I'm running 2DXtal through the GUI. Running "Init Program" through "Get Lattice" works just fine. Under "Custom," I use "Mask Crystal from Polygon." The resulting masked image looks correct, but when I then rerun "Calculate FFTs," I get the error, "cp: 'image_2dx_raw.mrc' and 'image_2dx.mrc' are the same file"

Thanks for the help,
Kelli


#################################2dx_fftrans##################################
 
############################################
# Parameters requested by the Script       #
############################################
phaseori_done = n
tempkeep = n
imagename = mimage_2dx
nonmaskimagename = image_2dx
imagenumber = 0000000001
imagesidelength = 3808
realcell = 100.0,100.0
magnification = 10000
stepdigitizer = 1.9
calc_from_sample_pixel = y
sample_pixel = 1.9
realang = 90.0
phacon = 0.995
resmin = 200.0
resmax = 4.0
radlim = 35.0,35.0,0.0
generateperiodogram = n
periodogramwindowsize = 512
periodogramnumsubsteps = 20
taperbeforefft = y
crop = 1
crop_histogram = y
crop_histogram_percent = 5
crop_histogram_stdev = 4.0
ctfcor_imode = 1
use_masked_image = y
movie_inmovie = n
movie_stackname = movie_aligned
 
############################################
# Parameters from the Preferences settings #
############################################
app_python = /usr/bin/python
app_cadaver = /usr/bin/cadaver
app_anaconda = /usr/bin/python
dir_ccp4 = /opt/applications/ccp4/7.0/ccp4-7.0
app_gawk = /usr/local/Cellar/gawk
cuda_library = /usr/local/cuda/lib64
app_unblur = /usr/local/cina/unblur/unblur_1.0.2/bin/unblur_openmp_7_17_15.exe
app_motioncor2 = /usr/local/cina/motioncor2/bin/motioncor2.exe
app_gctf = /opt/applications/modulefiles/applications/gctf/1.06
app_ctffind = /opt/applications/ctf/4.1.10/bin/ctffind4
app_gautomatch = /usr/local/cina/Gautomatch/0.50_cuda7.5/bin/gautomatch
dir_eman2 = /opt/applications/modulefiles/applications/eman
dir_imod = /usr/local/IMOD
dir_frealign = /opt/applications/modulefiles/applications/frealign
dir_relion = /opt/applications/modulefiles/applications/relion
Microscope_Name = CryoEM
Default_CS = 2.7
Default_KV = 300.0
Default_phase_shift_doit = n
status_folder_update = n
status_folder = none
status_microscope = Titan
status_refresh_rate = 0
status_webdav = http://my.server.com/files
website_blur_doit = y
website_blurkernel = 7
SCRATCH_DISK = .
FAST_DISK = .
GPU_how_many = 4
GPU_to_use = 0 1 2 3
GPU_cycle = n
MotionCor2_alone = y
notify_email_admin = y
notify_email_admin_adress = name@provider.com
notify_last_minutes = 15
notify_delay_minutes = 60
notify_lastnumber = 50
notify_limit_mild = 30
notify_limit_severe = 15
flag_isdark_threshold = 0.1
flag_hasstripe_threshold = 38.0
flag_hastoohighdefocus_threshold = 7.0
flag_hastoolowdefocus_threshold = 0.2
flag_icinesstoohigh_threshold = 1.6
flag_drifttoohigh_threshold = 50.0
flag_astigmatismtoohigh_threshold = 0.03
flag_ctfresolutiontoobad_threshold = 8.0
 
#############################################
# Now the remainder of the original script: #
#############################################
 
++++++++++++++++++++++++++++++++
Initializing script environment
++++++++++++++++++++++++++++++++
 
 Running the following shell:
  version tcsh 6.17.00 (Astron) 2009-07-10 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,color,filec
 
date = Mon Nov 4 10:10:37 PST 2019
system = Linux
bin_2dx = /opt/applications/focus/3.5.0/gnu/kernel/mrc/bin
proc_2dx = /opt/applications/focus/3.5.0/gnu/scripts/proc
==== dir_eman2 = /opt/applications/modulefiles/applications/eman ======================================================================================================================================
==== app_python = /usr/bin/python =====================================================================================================================================================================
==== app_anaconda = /usr/bin/python ===================================================================================================================================================================
==== dir_frealign = /opt/applications/modulefiles/applications/frealign ===============================================================================================================================
==== dir_relion = /opt/applications/modulefiles/applications/relion ===================================================================================================================================
 
=======================================================================================================================================================================================================
==== Sourcing 2dx_init_files_sub.com ==================================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Setting imagename to image_2dx.mrc ===============================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Testing if image_2dx.mrc exists ==================================================================================================================================================================
=======================================================================================================================================================================================================
 
 
=======================================================================================================================================================================================================
==== Copying image_2dx_raw.mrc onto image_2dx.mrc =====================================================================================================================================================
=======================================================================================================================================================================================================
 
############################2dx_fftrans finished.#############################
cp: `image_2dx_raw.mrc' and `image_2dx.mrc' are the same file

**Comment by sthennin** [comment] 2019-11-04 20:34
This should be fixed now. Please update to the latest version on GitHub.
Thanks,
Henning.

**Comment by klhvorecny** [comment] 2019-11-06 21:22
That did the trick.
Thank you,
Kelli

**Closed** 2019-11-27 17:10 UTC
